function [ACQ_TIME_TICS,CHANNEL,VALUE,SIGNAL] = importSiemens_PULS(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [ACQ_TIME_TICS,CHANNEL,VALUE,SIGNAL] = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [ACQ_TIME_TICS,CHANNEL,VALUE,SIGNAL] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [ACQ_TIME_TICS,CHANNEL,VALUE,SIGNAL] = importfile('Physio_20230113_153045_6d8c998b-f869-4b40-9a06-b7fb6657a3bf_PULS.txt',7, 13753);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2023/03/13 12:00:20

%% Initialize variables.
if nargin<=2
    startRow = 7;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%13f%9s%7f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Remove white space around all cell columns.
dataArray{2} = strtrim(dataArray{2});
dataArray{4} = strtrim(dataArray{4});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ACQ_TIME_TICS = dataArray{:, 1};
CHANNEL = dataArray{:, 2};
VALUE = dataArray{:, 3};
SIGNAL = dataArray{:, 4};


